server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ~ ^/(terms|privacy)/tiktok {
    default_type text/plain;
    try_files $uri =404;
  }

  location ~ ^/tiktok {
    default_type text/plain;
    try_files $uri =404;
  }

  location = /tiktok-callback { try_files /tiktok-callback.html =404; }

  location = /terms { try_files /terms.html =404; }
  location = /privacy { try_files /privacy.html =404; }
  location / { try_files $uri $uri/ /index.html; }
}
